version: '3'

#Volumes
volumes:
  dbdata:
    driver: local

services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-assets/nginx/conf.d/:/etc/nginx/conf.d/
    #networks:
    #  - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
    #  - ./docker-assets/dbdata:/var/lib/mysql
      - ./docker-assets/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    #command: --init-file ./docker-assets/scripts/init.sql
    #networks:
    #  - app-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-assets/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    #entrypoint: /docker-assets/scripts/setup.sh
    #networks:
    #  - app-network

#Docker Networks
#networks:
#  app-network:
#    driver: bridge

